name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Required for API access

      # Upload the generated SVG as a GitHub artifact
      - name: Upload Snake animation
        uses: actions/upload-artifact@v3
        with:
          name: github-snake
          path: dist/github-contribution-grid-snake.svg
