name: Generate Snake Animation

on:
  # Run automatically on a schedule (every 6 hours)
  schedule:
    - cron: "0 */6 * * *"
  # Run on each new commit to the repository
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          # the output path for the generated SVG
          output: dist/github-contribution-grid-snake.svg

      # Upload the generated SVG as a GitHub artifact
      - name: Upload Snake animation
        uses: actions/upload-artifact@v3
        with:
          name: github-snake
          path: dist/github-contribution-grid-snake.svg
